services:
  app:
    build: .
    image: antilavado:dev 
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app       
      - /usr/src/app/node_modules  
    environment:
      - NODE_ENV=development
    stdin_open: true  
    tty: true        

#   postgres:
#     image: postgres:16.8
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: antilavado
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
